/**
 * types of file upload actions
 */
export const UPLOAD_FILE_START = "UPLOAD_FILE_START";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILURE = "UPLOAD_FILE_FAILURE";

/**
 * types of joke fetch actions
 */
export const FETCH_JOKES_START = "FETCH_JOKES_START";
export const FETCH_JOKES_SUCCESS = "FETCH_JOKES_SUCCESS";
export const FETCH_JOKES_FAILURE = "FETCH_JOKES_FAILURE";

export const FETCH_USER_QUESTIONS_START = "FETCH_USER_QUESTIONS_START";
export const FETCH_USER_QUESTIONS_SUCCESS = "FETCH_USER_QUESTIONS_SUCCESS";
export const FETCH_USER_QUESTIONS_FAILURE = "FETCH_USER_QUESTIONS_FAILURE";


/**
 * types of auth actions
 */
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const USER_START = 'USER_START';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAIL = 'USER_FAIL';

export const FETCH_QUESTIONS_START = 'FETCH_QUESTIONS_START';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAIL = 'FETCH_QUESTIONS_FAIL';
export const CREATE_QUESTIONS_SUCCESS = 'CREATE_QUESTIONS_SUCCESS';
export const CREATE_QUESTIONS_ERROR = 'CREATE_QUESTIONS_ERROR';
export const EDIT_QUESTIONS_SUCCESS = 'EDIT_QUESTIONS_SUCCESS';
export const EDIT_QUESTIONS_ERROR = 'EDIT_QUESTIONS_ERROR';


/**
 * action types of getting scoreboard
 */
export const GET_SCOREBOARD_START = 'GET_SCOREBOARD_START';
export const GET_SCOREBOARD_SUCCESS = 'GET_SCOREBOARD_SUCCESS';
export const GET_SCOREBOARD_FAIL = 'GET_SCOREBOARD_FAIL';